services:
#    overscan_menu.example:
#        class: Overscan\Bundle\MenuBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    overscan_menu.admin.menu:
        class: Overscan\Bundle\MenuBundle\Admin\MenuAdmin
        arguments: [~, Overscan\Bundle\MenuBundle\Entity\Menu, OverscanMenuBundle:MenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contenus, label: Menu}

    overscan_bundle.menubundle.twig.menu_extension:
        class: Overscan\Bundle\MenuBundle\Twig\MenuExtension
        arguments: [ @doctrine ]
        tags:
            - { name: twig.extension }
