services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    overscan_menu.admin.menu:
        class: Overscan\Bundle\MenuBundle\Admin\MenuAdmin
        arguments: [~, Overscan\Bundle\MenuBundle\Entity\Menu, OverscanMenuBundle:MenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Contenus, label: Menu}

    overscan_bundle.menubundle.twig.menu_extension:
        class: Overscan\Bundle\MenuBundle\Twig\MenuExtension
        arguments: [ @doctrine ]
        tags:
            - { name: twig.extension }
