<?php

namespace Id4v\Bundle\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends EntityRepository
{
    public function getRootNodesBySlug($slug)
    {
        $query = $this->createQueryBuilder('item')
                ->join('item.menu', 'menu')
                ->where("menu.slug LIKE '".$slug."'")
                ->andWhere('item.parent is null');

        return $query->getQuery()->getResult();
    }
}
